image: python:3.13

before_script:
  - python -m pip install --upgrade pip
  - poetry install --no-root
  - poetry add --dev pylint pytest pytest-cov

stages:          # Список этапов для задач и их порядок выполнения
  - testing
  - build
  - deploy

lint:   # Эта задача выполняется на этапе тестирования.
  stage: testing
  script:
    - echo "Запуск линтинга..."
    - poetry run pylint $(git ls-files '*.py')

test:   # Эта задача выполняется на этапе тестирования.
  stage: testing
  script:
    - echo "Запуск тестов..."
    - poetry run pytest -s --cov --cov-report html --cov-fail-under=80

build-job:       # Эта задача выполняется на этапе сборки.
  stage: build
  script:
    - echo "Компиляция кода..."
    - echo "Компиляция завершена."

deploy-job:      # Эта задача выполняется на этапе развертывания.
  stage: deploy
  script:
    - echo "Развертывание приложения..."
    - echo "Приложение успешно развернуто."
